include: package:flutter_lints/flutter.yaml


analyzer:
  plugins:
    - custom_lint
  exclude: [lib/gen/**, lib/**.freezed.dart, lib/**.g.dart, lib/**.tailor.dart]

linter:
  rules:
    - require_trailing_commas
    - always_use_package_imports