targets:  
  $default:
    sources:
      - $package$ 
      - api_spec/**
      - lib/**
    builders:
      swagger_dart_code_generator:
        options:
          output_folder: 'lib/generated/api'
          input_folder: 'api_spec/'