name: cube_system
description: Modern electronic timetable
publish_to: 'none'
version: 0.8.2+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

  upgrader: 
    git:
      url: https://github.com/StarProxima/upgrader
  

  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  theme_tailor_annotation: ^2.0.0

  proxima_logger: ^0.6.3
  intl: ^0.18.0
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.2
  

  flutter_riverpod: ^2.3.6
  go_router: ^7.0.1
  chopper: ^6.1.1

  device_preview: ^1.1.0
  url_launcher: ^6.1.10
  rive: ^0.10.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_native_splash: ^2.2.19

  app_runner: ^2.1.2
  package_info_plus: ^3.0.1
  flutter_dotenv: ^5.0.2
  appmetrica_plugin: ^1.1.0


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  swagger_dart_code_generator: ^2.11.0

  flutter_lints: ^2.0.1
  lints: ^2.0.1

  freezed: ^2.3.2
  json_serializable: ^6.6.1
  theme_tailor: ^2.0.0

  build_runner:
  flutter_gen_runner:
  chopper_generator: ^6.0.0
  flutter_launcher_icons: ^0.13.1

  custom_lint:
  riverpod_lint:
  hive_generator: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/brooklyn/
    - assets/icons/
    - assets/icons/cube_logo.svg
    - assets/rive/
    - assets/rive/shapes.riv
    - assets/images/
    - assets/images/spline.png


flutter_gen:
  output: lib/gen/assets
  integrations:
    flutter_svg: true
    rive: true


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/cube_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true


flutter_native_splash:
  color: "#F6F7FF"
  android_12:
    color: "#F6F7FF"

